### ISSUE TITLE
acquireTokenWithDeviceCode doesn't block as expected

### ISSUE THREAD

**Issue by thenewwazoo** [AzureAD/azure-activedirectory-library-for-nodejs#137]
When running the device-code-sample.js example, the acquireTokenWithDevice code function doesn't appear to block as expected (or is polling too quickly?). This unfortunately results in the device auth flow being unusable.

The response from acquireUserCode looks good, but as you can see from the verbose output below, the polling happens rather quickly, and the callback is called with an error almost immediately.

```
Wed, 19 Oct 2016 16:29:44 GMT:03092e48-6352-42e2-9eea-bec1f3b20d6c - Authority: VERBOSE: Performing instance discovery: https://login.windows.net/microsoft.com
Wed, 19 Oct 2016 16:29:44 GMT:03092e48-6352-42e2-9eea-bec1f3b20d6c - Authority: VERBOSE: Performing static instance discovery
Wed, 19 Oct 2016 16:29:44 GMT:03092e48-6352-42e2-9eea-bec1f3b20d6c - Authority: VERBOSE: Authority validated via static instance discovery.
Wed, 19 Oct 2016 16:29:44 GMT:03092e48-6352-42e2-9eea-bec1f3b20d6c - DeviceCodeRequest: INFO: Getting user code info.
Wed, 19 Oct 2016 16:29:45 GMT:03092e48-6352-42e2-9eea-bec1f3b20d6c - OAuth2Client: INFO: Get Device Code Server returned this correlationId: 03092e48-6352-42e2-9eea-bec1f3b20d6c
{ userCode: '...',
  deviceCode: '...',
  verificationUrl: 'https://login.windows.net/common/oauth2/deviceauth',
  expiresIn: 900,
  interval: 5,
  message: 'To sign in, use a web browser to open the page https://login.windows.net/common/oauth2/deviceauth. Enter the code BDMZTKVQM to authenticate.' }
calling acquire token with device code
Wed, 19 Oct 2016 16:29:45 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - Authority: VERBOSE: Instance discovery/validation has either already been completed or is turned off: https://login.windows.net/microsoft.com
Wed, 19 Oct 2016 16:29:45 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - TokenRequest: INFO: Getting a token via device code
Wed, 19 Oct 2016 16:29:46 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: INFO: Get TokenServer returned this correlationId: 02c9684c-b36c-423a-a78d-68ff007b0dbd
Wed, 19 Oct 2016 16:29:46 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: e98b71e5-a15b-4e02-a7a2-f6716bd045ff\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:46Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:46Z","trace_id":"e98b71e5-a15b-4e02-a7a2-f6716bd045ff","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: e98b71e5-a15b-4e02-a7a2-f6716bd045ff\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:46Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:46Z","trace_id":"e98b71e5-a15b-4e02-a7a2-f6716bd045ff","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
    at Logger.createError (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/log.js:201:13)
    at Request._callback (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/util.js:133:25)
    at Request.self.callback (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1111:12)
    at emitNone (events.js:72:20)
[Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: e98b71e5-a15b-4e02-a7a2-f6716bd045ff\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:46Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:46Z","trace_id":"e98b71e5-a15b-4e02-a7a2-f6716bd045ff","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}]
Wed, 19 Oct 2016 16:29:46 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: INFO: Get TokenServer returned this correlationId: 02c9684c-b36c-423a-a78d-68ff007b0dbd
Wed, 19 Oct 2016 16:29:46 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: cd417f24-8d41-4d02-89bf-f8fc974e887f\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"cd417f24-8d41-4d02-89bf-f8fc974e887f","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: cd417f24-8d41-4d02-89bf-f8fc974e887f\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"cd417f24-8d41-4d02-89bf-f8fc974e887f","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
    at Logger.createError (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/log.js:201:13)
    at Request._callback (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/util.js:133:25)
    at Request.self.callback (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1111:12)
    at emitNone (events.js:72:20)
[Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: cd417f24-8d41-4d02-89bf-f8fc974e887f\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"cd417f24-8d41-4d02-89bf-f8fc974e887f","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}]
Wed, 19 Oct 2016 16:29:47 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: INFO: Get TokenServer returned this correlationId: 02c9684c-b36c-423a-a78d-68ff007b0dbd
Wed, 19 Oct 2016 16:29:47 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: f7f987a0-5241-43c9-8103-308c21b1d5b9\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"f7f987a0-5241-43c9-8103-308c21b1d5b9","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: f7f987a0-5241-43c9-8103-308c21b1d5b9\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"f7f987a0-5241-43c9-8103-308c21b1d5b9","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
    at Logger.createError (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/log.js:201:13)
    at Request._callback (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/util.js:133:25)
    at Request.self.callback (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1111:12)
    at emitNone (events.js:72:20)
[Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: f7f987a0-5241-43c9-8103-308c21b1d5b9\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"f7f987a0-5241-43c9-8103-308c21b1d5b9","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}]
Wed, 19 Oct 2016 16:29:47 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: INFO: Get TokenServer returned this correlationId: 02c9684c-b36c-423a-a78d-68ff007b0dbd
Wed, 19 Oct 2016 16:29:47 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 4726d1d7-99e0-4db8-8f4a-27deef715efe\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"4726d1d7-99e0-4db8-8f4a-27deef715efe","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 4726d1d7-99e0-4db8-8f4a-27deef715efe\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"4726d1d7-99e0-4db8-8f4a-27deef715efe","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
    at Logger.createError (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/log.js:201:13)
    at Request._callback (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/util.js:133:25)
    at Request.self.callback (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1111:12)
    at emitNone (events.js:72:20)
[Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 4726d1d7-99e0-4db8-8f4a-27deef715efe\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:47Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:47Z","trace_id":"4726d1d7-99e0-4db8-8f4a-27deef715efe","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}]
Wed, 19 Oct 2016 16:29:48 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: INFO: Get TokenServer returned this correlationId: 02c9684c-b36c-423a-a78d-68ff007b0dbd
Wed, 19 Oct 2016 16:29:48 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 0c2f1983-ff29-41a8-b0a1-8597300ebdd0\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:48Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:48Z","trace_id":"0c2f1983-ff29-41a8-b0a1-8597300ebdd0","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 0c2f1983-ff29-41a8-b0a1-8597300ebdd0\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:48Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:48Z","trace_id":"0c2f1983-ff29-41a8-b0a1-8597300ebdd0","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}
    at Logger.createError (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/log.js:201:13)
    at Request._callback (/Users/brmatt/Development/ALTAR/tmp/azure-activedirectory-library-for-nodejs/lib/util.js:133:25)
    at Request.self.callback (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/brmatt/Development/ALTAR/node_modules/request/request.js:1111:12)
    at emitNone (events.js:72:20)
[Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 0c2f1983-ff29-41a8-b0a1-8597300ebdd0\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:48Z","error_codes":[70016],"timestamp":"2016-10-19 16:29:48Z","trace_id":"0c2f1983-ff29-41a8-b0a1-8597300ebdd0","correlation_id":"02c9684c-b36c-423a-a78d-68ff007b0dbd"}]
Wed, 19 Oct 2016 16:29:48 GMT:02c9684c-b36c-423a-a78d-68ff007b0dbd - TokenRequest: VERBOSE: Token polling request returend with err.
error happens when acquiring token with device code
{ error: 'authorization_pending',
  error_description: 'AADSTS70016: Pending end-user authorization.\r\nTrace ID: 0c2f1983-ff29-41a8-b0a1-8597300ebdd0\r\nCorrelation ID: 02c9684c-b36c-423a-a78d-68ff007b0dbd\r\nTimestamp: 2016-10-19 16:29:48Z',
  error_codes: [ 70016 ],
  timestamp: '2016-10-19 16:29:48Z',
  trace_id: '0c2f1983-ff29-41a8-b0a1-8597300ebdd0',
  correlation_id: '02c9684c-b36c-423a-a78d-68ff007b0dbd' }
```

**Comment by thenewwazoo** [comment]
This looks like it is probably related to older versions (older than 1.2.0?) of async requiring an integer for the retry argument, and not accepting an opts object.

**Comment by thenewwazoo** [comment]
Yep. Updating to async 2.1.2 resolved the problem. Not sure how I ended up with 0.9.2 but there you go.

**Comment by ramijarrar** [comment]
Was facing the same issue recently and had to add "async" to my top level dependencies to work-around this, is there a reason why the listed version couldn't be updated to >=1.2.0?
