### ISSUE TITLE
Socket Hang Up Error w/ client-credentials-sample.js

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-library-for-nodejs#93]
Hi, 

I was wondering if you could help me with this socket hang up error I'm encountering. I encounter the same issue with other sample code of O365-Nodejs.

System: OS X Yosemite 10.10.5
Node version: tried with both v0.10.25 and v0.12.9

Steps: 
1. create an empty directory & cd into it
1. `npm init`
2. `npm install adal-node --save`
3. `touch index.js`, populate with a simplified version of adal-node/sample/client-credentials-sample.js, as below

```
//INDEX.JS
'use strict';
var fs = require('fs'),
    adal = require('adal-node');
var AuthenticationContext = adal.AuthenticationContext;
function turnOnLogging() {...}

var params = {
    tenant: 'fiveblocksup.onmicrosoft.com',
    authorityHostUrl: 'https://login.windows.net', //'https://login.microsoftonline.com/common', //TRIED BOTH
    clientId: 'validClientId',
    clientSecret: 'validSecret='
};

var authorityUrl = params.authorityHostUrl + '/' + params.tenant;
var resource = '00000002-0000-0000-c000-000000000000'; //not sure what this is for
turnOnLogging();
var context = new AuthenticationContext(authorityUrl);
context.acquireTokenWithClientCredentials(resource, params.clientId, params.clientSecret, function (err, tokenResponse) {
    if(err){
        console.log('######### ERROR #############');
        console.log(err.stack);
        console.log('#########  END  #############');
    } else {
        console.log(tokenResponse);
    }
});
```

This is the error I get: 

```
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - Authority: VERBOSE: Performing instance discovery: https://login.windows.net/fiveblocksup.onmicrosoft.com
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - Authority: VERBOSE: Performing static instance discovery
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - Authority: VERBOSE: Authority validated via static instance discovery.
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - TokenRequest: INFO: Getting token with client credentials.
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - TokenRequest: VERBOSE: No userId passed for cache query.
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - CacheDriver: VERBOSE: finding with query:{"clientId":"validClientId"}
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - CacheDriver: VERBOSE: Looking for potential cache entries:
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - CacheDriver: VERBOSE: {"_clientId":"validClientId"}
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - CacheDriver: VERBOSE: Found 0 potential entries.
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - TokenRequest: VERBOSE: No appropriate cached token found.
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - OAuth2Client: ERROR: Get Token request failed with
Stack:
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:300:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
{ [Error: socket hang up] code: 'ECONNRESET' }
Tue, 08 Dec 2015 22:15:01 GMT:4d55c64f-c7da-416c-8e9e-1afa46f2ef45 - TokenRequest: VERBOSE: getTokenFunc returned with err
######### ERROR #############
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:300:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
#########  END  #############
```

**Comment by weijjia** [comment]
Do you have a fiddler trace?Fiddler trace will give a better idea on what's happening over the wire.

**Comment by jmckennon** [comment]
Closing as it's been quite a bit of time, so we're assuming this is no longer a problem.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
